/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    DbSlug: typeof import('./components/DbSlug.vue')['default']
    Deploy: typeof import('./components/Deploy.vue')['default']
    FileTree: typeof import('./components/FileTree.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tracking: typeof import('./components/Tracking.vue')['default']
    Tree: typeof import('./components/Tree.vue')['default']
    TreeNode: typeof import('./components/TreeNode.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
  }
}
