/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAbout: typeof import("./components/AppAbout.vue")["default"]
    AppLanding: typeof import("./components/AppLanding.vue")["default"]
    AppNav: typeof import("./components/AppNav.vue")["default"]
    AppNotifier: typeof import("./components/AppNotifier.vue")["default"]
    AppPortfolio: typeof import("./components/AppPortfolio.vue")["default"]
    Auth: typeof import('./components/Auth.vue')['default']
    Camera: typeof import("./components/Camera.vue")["default"]
    Chart: typeof import("./components/Chart.vue")["default"]
    Dark: typeof import('./components/Dark.vue')['default']
    DbSlug: typeof import('./components/DbSlug.vue')['default']
    Deploy: typeof import('./components/Deploy.vue')['default']
    Deployments: typeof import("./components/Deployments.vue")["default"]
    FileTree: typeof import('./components/FileTree.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import("./components/HelloWorld.vue")["default"]
    Landing: typeof import('./components/Landing.vue')['default']
    NavBar: typeof import("./components/NavBar.vue")["default"]
    Notifier: typeof import('./components/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Social: typeof import("./components/Social.vue")["default"]
    SystemBar: typeof import("./components/SystemBar.vue")["default"]
    TikTok: typeof import("./components/TikTok.vue")["default"]
    Tracking: typeof import('./components/Tracking.vue')['default']
    Tree: typeof import('./components/Tree.vue')['default']
    TreeItem: typeof import("./components/TreeItem.vue")["default"]
    TreeNode: typeof import('./components/TreeNode.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
  }
}
